{
    "openapi": "3.0.0",
    "info": {
      "title": "chat_api",
      "contact": "garciavillegasjonathan@gmail.com",
      "description": "...",
      "version": "1.0"
    },
    "paths": {
      "/api/v1/users": {
        "post": {
          "tags": [
            "users"
          ],
          "summary": "register",
          "operationId": "register",
          "parameters": [],
          "requestBody": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/registerrequest"
                    },
                    {
                      "example": {
                        "firstname": "Shin",
                        "lastname": "Nouzen",
                        "email": "shin@gmail.com",
                        "password": "Greco1234*"
                      }
                    }
                  ]
                },
                "example": {
                  "firstname": "Shin",
                  "lastname": "Nouzen",
                  "email": "shin@gmail.com",
                  "password": "Greco1234*"
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        },
        "get": {
            "security": [
                {
                  "bearer": []
                }
              ],
          "tags": [
            "users"
          ],
          "summary": "get all users",
          "operationId": "getallusers",
          "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }
      },
      "/api/v1/users/login": {
        "post": {
          "tags": [
            "users"
          ],
          "summary": "login",
          "operationId": "login",
          "parameters": [],
          "requestBody": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/loginrequest"
                    },
                    {
                      "example": {
                        "email": "jgv.077@gmail.com",
                        "password": "Greco1234*"
                      }
                    }
                  ]
                },
                "example": {
                  "email": "jgv.077@gmail.com",
                  "password": "Greco1234*"
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }
      },
      "/api/v1/users/login/reverify-email": {
        "post": {
          "tags": [
            "users"
          ],
          "summary": "reverify-email",
          "operationId": "reverify-email",
          "parameters": [],
          "requestBody": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/reverify-email-request"
                    },
                    {
                      "example": {
                        "email": "jgv.077@gmail.com"
                      }
                    }
                  ]
                },
                "example": {
                  "email": "jgv.077@gmail.com"
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }
      },
      "/api/v1/conversations": {
        "post": {
            "security": [
                {
                  "bearer": []
                }
              ],
          "tags": [
            "conversations"
          ],
          "summary": "createConversation",
          "operationId": "createConversation",
          "parameters": [],
          "requestBody": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/createConversationRequest"
                    },
                    {
                      "example": {
                        "userId": 1,
                        "participantId": 2
                      }
                    }
                  ]
                },
                "example": {
                  "userId": 1,
                  "participantId": 2
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }
      },
      "/api/v1/conversations/group": {
        "post": {
            "security": [
                {
                  "bearer": []
                }
              ],
          "tags": [
            "conversations"
          ],
          "summary": "create group conversation",
          "operationId": "creategroupconversation",
          "parameters": [],
          "requestBody": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/creategroupconversationrequest"
                    },
                    {
                      "example": {
                        "userId": 1,
                        "participantsIds": [
                          2,
                          3,
                          4,
                          5
                        ],
                        "title": "ParanguaTeam"
                      }
                    }
                  ]
                },
                "example": {
                  "userId": 1,
                  "participantsIds": [
                    2,
                    3,
                    4,
                    5
                  ],
                  "title": "ParanguaTeam"
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }
      },
      "/api/v1/conversations/{id}": {
        "get": {
            "security": [
                {
                  "bearer": []
                }
              ],
          "tags": [
            "conversations"
          ],
          "summary": "get all conversations by user",
          "operationId": "getallconversationsbyuser",
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "description": "",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "integer",
                "format": "int32",
                "example": 1
              }
            }
          ],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }
      },
      "/api/v1/messages/conversation/{id}": {
        "post": {
          "tags": [
            "messages"
          ],
          "summary": "create new message",
          "operationId": "createnewmessage",
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "description": "",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "integer",
                "format": "int32",
                "example": 1
              }
            }
          ],
          "requestBody": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/createnewmessagerequest"
                    },
                    {
                      "example": {
                        "content": "Im sorry sensei i was a little bussy, how are u?!",
                        "senderId": 2
                      }
                    }
                  ]
                },
                "example": {
                  "content": "Im sorry sensei i was a little bussy, how are u?!",
                  "senderId": 2
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        },
        "get": {
          "tags": [
            "messages"
          ],
          "summary": "get conversations messages",
          "operationId": "getconversationsmessages",
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "description": "",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "integer",
                "format": "int32",
                "example": 1
              }
            }
          ],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        }
      },
      "/api/v1/users/{id}": {
        "put": {
          "tags": [
            "Misc"
          ],
          "summary": "upload avatar",
          "operationId": "uploadavatar",
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "description": "",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "integer",
                "format": "int32",
                "example": 2
              }
            }
          ],
          "requestBody": {
            "content": {
              "multipart/form-data": {
                "encoding": {},
                "schema": {
                  "required": [
                    "avatar"
                  ],
                  "type": "object",
                  "properties": {
                    "avatar": {
                      "type": "string",
                      "format": "binary"
                    }
                  }
                }
              }
            },
            "required": false
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        }
      }
    },
    "components": {
      "schemas": {
        "registerrequest": {
          "title": "registerrequest",
          "required": [
            "firstname",
            "lastname",
            "email",
            "password"
          ],
          "type": "object",
          "properties": {
            "firstname": {
              "type": "string"
            },
            "lastname": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "password": {
              "type": "string"
            }
          },
          "example": {
            "firstname": "Shin",
            "lastname": "Nouzen",
            "email": "shin@gmail.com",
            "password": "Greco1234*"
          }
        },
        "loginrequest": {
          "title": "loginrequest",
          "required": [
            "email",
            "password"
          ],
          "type": "object",
          "properties": {
            "email": {
              "type": "string"
            },
            "password": {
              "type": "string"
            }
          },
          "example": {
            "email": "jgv.077@gmail.com",
            "password": "Greco1234*"
          }
        },
        "reverify-email-request": {
          "title": "reverify-email-request",
          "required": [
            "email"
          ],
          "type": "object",
          "properties": {
            "email": {
              "type": "string"
            }
          },
          "example": {
            "email": "jgv.077@gmail.com"
          }
        },
        "createConversationRequest": {
          "title": "createConversationRequest",
          "required": [
            "userId",
            "participantId"
          ],
          "type": "object",
          "properties": {
            "userId": {
              "type": "integer",
              "format": "int32"
            },
            "participantId": {
              "type": "integer",
              "format": "int32"
            }
          },
          "example": {
            "userId": 1,
            "participantId": 2
          }
        },
        "creategroupconversationrequest": {
          "title": "creategroupconversationrequest",
          "required": [
            "userId",
            "participantsIds",
            "title"
          ],
          "type": "object",
          "properties": {
            "userId": {
              "type": "integer",
              "format": "int32"
            },
            "participantsIds": {
              "type": "array",
              "items": {
                "type": "integer",
                "format": "int32"
              },
              "description": ""
            },
            "title": {
              "type": "string"
            }
          },
          "example": {
            "userId": 1,
            "participantsIds": [
              2,
              3,
              4,
              5
            ],
            "title": "ParanguaTeam"
          }
        },
        "createnewmessagerequest": {
          "title": "createnewmessagerequest",
          "required": [
            "content",
            "senderId"
          ],
          "type": "object",
          "properties": {
            "content": {
              "type": "string"
            },
            "senderId": {
              "type": "integer",
              "format": "int32"
            }
          },
          "example": {
            "content": "Im sorry sensei i was a little bussy, how are u?!",
            "senderId": 2
          }
        }
      },
      "securitySchemes": {
        "bearer": {
          "type": "http",
          "scheme": "bearer"
        }
      }
    },
    "security": [],
    "tags": [
      {
        "name": "users"
      },
      {
        "name": "conversations"
      },
      {
        "name": "messages"
      },
      {
        "name": "Misc",
        "description": ""
      }
    ]
  }